version: 2
# following https://stackoverflow.com/questions/44773415/how-to-push-a-commit-to-github-from-a-circleci-build-using-a-personal-access-tok

jobs:
  wakeupherokuapp:
    machine: true
    steps:
      - run:
          name: wake up heroku app
          working_directory: ~/workdir
          command: |
            echo 'waking up heroku app'
            curl -d '{"station": "drehbrucke"}' -X POST -H "Content-Type: application/json" https://tram-bot.herokuapp.com/station
            echo 'curl done'
            echo 'End waking up heroku app'

workflows:
  version: 2
  morning:
    triggers:
      - schedule:
          cron: "0 6-9 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - wakeupherokuapp
  morning30:
    triggers:
      - schedule:
          cron: "30 6-9 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - wakeupherokuapp
  noon:
    triggers:
      - schedule:
          cron: "0 10-13 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - wakeupherokuapp
  noon30:
    triggers:
      - schedule:
          cron: "30 10-13 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - wakeupherokuapp
  evening0:
    triggers:
      - schedule:
          cron: "0 15-19 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - wakeupherokuapp
  evening20:
    triggers:
      - schedule:
          cron: "20 15-19 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - wakeupherokuapp
  evening40:
    triggers:
      - schedule:
          cron: "40 15-19 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - wakeupherokuapp
